CREATE DATABASE `etelfutar` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE IF NOT EXISTS `database1`.`ORDER` (
  `USER_ID` INT NOT NULL,
  `ETEL_ID` INT NOT NULL,
  `DATE` DATE NOT NULL,
  `DONE` TINYINT NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `ORDER_ID` INT NOT NULL,
  PRIMARY KEY (`ORDER_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `database1`.`FOOD` (
  `FOOD_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `PRICE` INT NOT NULL DEFAULT 0,
  `CAT` VARCHAR(45) NOT NULL,
  `DB` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `database1`.`STAFF` (
  `STAFF_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `PRIORITY` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`STAFF_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `database1`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Tel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB